version: '3.8'

services:
  fastapi_app:
    image: rhn21/real-time-code-editor-ai-app:latest  
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
