version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./data:/app/data  # Persist SQLite data in a local folder

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6380:6379"
