name: CD Pipeline

on:
  push:
    branches:
      - dev  # Trigger on push to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "127.0.0.1"
          username: ${{ secrets.DOCKER_USERNAME }}
          key: ${{ secrets.DOCKER_PASSWORD }}
          script: |
            docker pull rhn21/real-time-code-editor-ai-app:latest
            docker stop fastapi_app || true
            docker rm fastapi_app || true
            docker run -d --name fastapi_app -p 8000:8000 --network app_network rhn21/real-time-code-editor-ai-app:latest
